# Generated by Django 2.2.3 on 2019-07-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('main_state', models.CharField(choices=[('QLD', 'QLD'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('ACT', 'ACT'), ('TAS', 'TAS'), ('SA', 'SA'), ('WA', 'WA'), ('NT', 'NT')], max_length=3)),
                ('sector', models.CharField(choices=[('DISTRIBUTION', 'DISTRIBUTION'), ('TRANSMISSION', 'TRANSMISSION')], max_length=20)),
            ],
        ),
    ]
